/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbSmokeRouteImport } from './routes/db-smoke'
import { Route as IndexRouteImport } from './routes/index'

const DbSmokeRoute = DbSmokeRouteImport.update({
  id: '/db-smoke',
  path: '/db-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db-smoke': typeof DbSmokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db-smoke': typeof DbSmokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db-smoke': typeof DbSmokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db-smoke'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db-smoke'
  id: '__root__' | '/' | '/db-smoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbSmokeRoute: typeof DbSmokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/db-smoke': {
      id: '/db-smoke'
      path: '/db-smoke'
      fullPath: '/db-smoke'
      preLoaderRoute: typeof DbSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbSmokeRoute: DbSmokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
